import type { Review } from '@/lib/types'

export const sampleReviews: Review[] = [
  {
    id: 'rev-001',
    skillId: 'mp-001',
    userId: 'user-001',
    userName: 'Sarah Chen',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    rating: 5,
    title: 'Essential for our DevOps workflow',
    comment: 'This GitHub issue tracker has been a game-changer for our team. The automatic labeling based on content is incredibly accurate, and the sentiment analysis helps us prioritize which issues need immediate attention. Setup was straightforward, and it integrates seamlessly with our existing tools. Highly recommend!',
    helpful: 42,
    notHelpful: 2,
    verified: true,
    timestamp: Date.now() - 15 * 24 * 60 * 60 * 1000
  },
  {
    id: 'rev-002',
    skillId: 'mp-001',
    userId: 'user-002',
    userName: 'Mike Rodriguez',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mike',
    rating: 4,
    title: 'Great tool, minor setup issues',
    comment: 'Overall very satisfied with this skill. The monitoring capabilities are excellent and notifications are timely. I did encounter some initial setup issues with the GitHub token configuration, but the documentation helped me resolve it. Would be nice to have more customization options for the labeling rules.',
    helpful: 28,
    notHelpful: 3,
    verified: true,
    timestamp: Date.now() - 8 * 24 * 60 * 60 * 1000
  },
  {
    id: 'rev-003',
    skillId: 'mp-001',
    userId: 'user-003',
    userName: 'Alex Park',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex',
    rating: 5,
    title: 'Perfect for open source projects',
    comment: "We maintain several open source projects and this has saved us countless hours. The priority detection is spot-on and helps us triage issues much faster. It's free, reliable, and does exactly what it promises. Thank you to the OpenClaw team!",
    helpful: 35,
    notHelpful: 0,
    verified: true,
    timestamp: Date.now() - 3 * 24 * 60 * 60 * 1000
  },
  {
    id: 'rev-004',
    skillId: 'mp-002',
    userId: 'user-004',
    userName: 'Jessica Williams',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jessica',
    rating: 5,
    title: 'Incredible AI-powered responses',
    comment: 'This email responder has transformed how we handle customer inquiries. The responses are natural, contextually appropriate, and maintain our brand voice perfectly. Worth every penny for the time it saves our support team. We\'ve seen a 60% reduction in response time.',
    helpful: 67,
    notHelpful: 1,
    verified: true,
    timestamp: Date.now() - 20 * 24 * 60 * 60 * 1000
  },
  {
    id: 'rev-005',
    skillId: 'mp-002',
    userId: 'user-005',
    userName: 'David Kumar',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David',
    rating: 4,
    title: 'Good but needs more customization',
    comment: 'The AI responses are generally quite good, but I wish there were more options to fine-tune the tone and style. Sometimes the responses are a bit too formal for our casual brand. That said, it handles complex queries well and the context awareness is impressive.',
    helpful: 23,
    notHelpful: 5,
    verified: true,
    timestamp: Date.now() - 12 * 24 * 60 * 60 * 1000
  },
  {
    id: 'rev-006',
    skillId: 'mp-003',
    userId: 'user-006',
    userName: 'Emily Zhang',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emily',
    rating: 5,
    title: 'Enterprise-grade security tool',
    comment: 'Absolutely essential for any serious development team. The OWASP Top 10 coverage is comprehensive, the compliance reports are audit-ready, and it caught several vulnerabilities our previous tools missed. The automated remediation suggestions are particularly helpful. This is the gold standard.',
    helpful: 89,
    notHelpful: 2,
    verified: true,
    timestamp: Date.now() - 25 * 24 * 60 * 60 * 1000
  },
  {
    id: 'rev-007',
    skillId: 'mp-003',
    userId: 'user-007',
    userName: 'Robert Taylor',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Robert',
    rating: 5,
    title: 'Best security investment we made',
    comment: 'As a security engineer, I\'m impressed by the depth of analysis this tool provides. The dependency checks are thorough, the CVE database integration is current, and the compliance reporting has streamlined our SOC2 process significantly. Well worth the investment.',
    helpful: 76,
    notHelpful: 0,
    verified: true,
    timestamp: Date.now() - 18 * 24 * 60 * 60 * 1000
  },
  {
    id: 'rev-008',
    skillId: 'mp-004',
    userId: 'user-008',
    userName: 'Lisa Anderson',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Lisa',
    rating: 5,
    title: 'Content creation made effortless',
    comment: 'This suite has revolutionized our content workflow. The SEO optimization is fantastic, the tone control gives us exactly what we need, and the quality is consistently high across all content types. We\'ve cut our content production time by 70% while maintaining quality.',
    helpful: 54,
    notHelpful: 3,
    verified: true,
    timestamp: Date.now() - 10 * 24 * 60 * 60 * 1000
  },
  {
    id: 'rev-009',
    skillId: 'mp-004',
    userId: 'user-009',
    userName: 'James Wilson',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=James',
    rating: 4,
    title: 'Great for most content needs',
    comment: 'Very solid content generation tool. Handles blog posts and social media excellently. The multi-language support is a huge plus. Only gripe is that sometimes it needs a bit of editing for very technical topics, but that\'s expected. Overall, great value.',
    helpful: 31,
    notHelpful: 4,
    verified: true,
    timestamp: Date.now() - 6 * 24 * 60 * 60 * 1000
  },
  {
    id: 'rev-010',
    skillId: 'mp-005',
    userId: 'user-010',
    userName: 'Rachel Green',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rachel',
    rating: 5,
    title: 'Deployment made simple',
    comment: 'As someone who was intimidated by smart contract deployment, this tool has been a lifesaver. The verification process is automatic, the multi-network support is seamless, and the testing features caught issues before they went live. Absolutely worth it for web3 developers.',
    helpful: 45,
    notHelpful: 1,
    verified: true,
    timestamp: Date.now() - 14 * 24 * 60 * 60 * 1000
  },
  {
    id: 'rev-011',
    skillId: 'mp-006',
    userId: 'user-011',
    userName: 'Chris Martinez',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Chris',
    rating: 5,
    title: 'Transformed our support operations',
    comment: 'This AI agent has genuinely reduced our support load by 60% as advertised. The sentiment analysis routes urgent issues to humans immediately, while handling routine queries autonomously. Our customers are happier, our team is less stressed, and our metrics have never been better.',
    helpful: 92,
    notHelpful: 2,
    verified: true,
    timestamp: Date.now() - 22 * 24 * 60 * 60 * 1000
  },
  {
    id: 'rev-012',
    skillId: 'mp-006',
    userId: 'user-012',
    userName: 'Nina Patel',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Nina',
    rating: 4,
    title: 'Excellent automation with minor limits',
    comment: 'The multi-channel support is fantastic and the knowledge base integration works well. Sometimes struggles with very complex technical queries, but that\'s understandable. The 24/7 availability alone makes this worthwhile. Great for scaling support operations.',
    helpful: 38,
    notHelpful: 3,
    verified: true,
    timestamp: Date.now() - 9 * 24 * 60 * 60 * 1000
  },
  {
    id: 'rev-013',
    skillId: 'mp-007',
    userId: 'user-013',
    userName: 'Tom Brown',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Tom',
    rating: 5,
    title: 'All-in-one social media solution',
    comment: 'Managing 5 social media accounts was overwhelming until I found this. The scheduling is intuitive, analytics are comprehensive, and the engagement tracking helps us understand what content works. The competitor analysis feature is the cherry on top.',
    helpful: 48,
    notHelpful: 2,
    verified: true,
    timestamp: Date.now() - 17 * 24 * 60 * 60 * 1000
  },
  {
    id: 'rev-014',
    skillId: 'mp-008',
    userId: 'user-014',
    userName: 'Sophie Lee',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sophie',
    rating: 5,
    title: 'ML made accessible',
    comment: 'I don\'t have a deep ML background, but this tool made it possible for me to train and deploy production-ready models. The AutoML features are incredibly powerful, and the one-click deployment saved us weeks of DevOps work. Absolutely recommended for teams without dedicated ML engineers.',
    helpful: 63,
    notHelpful: 1,
    verified: true,
    timestamp: Date.now() - 11 * 24 * 60 * 60 * 1000
  },
  {
    id: 'rev-015',
    skillId: 'mp-009',
    userId: 'user-015',
    userName: 'Marcus Johnson',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Marcus',
    rating: 5,
    title: 'Professional API management',
    comment: 'This gateway solution is exactly what we needed. The rate limiting is configurable, caching improved our response times dramatically, and the monitoring gives us visibility we never had before. DDoS protection is robust. Enterprise quality at a fair price.',
    helpful: 71,
    notHelpful: 1,
    verified: true,
    timestamp: Date.now() - 19 * 24 * 60 * 60 * 1000
  },
  {
    id: 'rev-016',
    skillId: 'mp-010',
    userId: 'user-016',
    userName: 'Amanda Foster',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Amanda',
    rating: 5,
    title: 'Best crypto portfolio tracker',
    comment: 'Tracks everything - coins, NFTs, DeFi positions, staking rewards. The real-time updates are accurate, tax reporting saves me hours during tax season, and price alerts have helped me catch several good trading opportunities. The 5000+ coin support means it handles all my holdings.',
    helpful: 58,
    notHelpful: 2,
    verified: true,
    timestamp: Date.now() - 7 * 24 * 60 * 60 * 1000
  },
  {
    id: 'rev-017',
    skillId: 'mp-011',
    userId: 'user-017',
    userName: 'Kevin Wright',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Kevin',
    rating: 4,
    title: 'Solid email marketing platform',
    comment: 'The campaign builder is user-friendly, A/B testing gives us valuable insights, and the segmentation features are powerful. Integration with our ESP was smooth. Would love to see more template options, but overall it\'s a comprehensive solution that delivers results.',
    helpful: 29,
    notHelpful: 4,
    verified: true,
    timestamp: Date.now() - 13 * 24 * 60 * 60 * 1000
  },
  {
    id: 'rev-018',
    skillId: 'mp-012',
    userId: 'user-018',
    userName: 'Olivia Martin',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Olivia',
    rating: 5,
    title: 'Video processing powerhouse',
    comment: 'Handles all our video processing needs effortlessly. Transcoding is fast, compression maintains quality, and the thumbnail generation is smart. We process hundreds of videos weekly and this has been rock solid. The S3/CDN integration made deployment a breeze.',
    helpful: 41,
    notHelpful: 1,
    verified: true,
    timestamp: Date.now() - 16 * 24 * 60 * 60 * 1000
  },
  {
    id: 'rev-019',
    skillId: 'mp-013',
    userId: 'user-019',
    userName: 'Daniel Kim',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Daniel',
    rating: 5,
    title: 'Analytics with ML insights',
    comment: 'The predictive analytics have helped us make better business decisions, and the anomaly detection caught issues we would have missed otherwise. The D3.js visualizations are beautiful and customizable. Integration with our data sources was straightforward. Excellent tool.',
    helpful: 55,
    notHelpful: 2,
    verified: true,
    timestamp: Date.now() - 21 * 24 * 60 * 60 * 1000
  },
  {
    id: 'rev-020',
    skillId: 'mp-014',
    userId: 'user-020',
    userName: 'Grace Thompson',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Grace',
    rating: 4,
    title: 'Comprehensive PDF processing',
    comment: 'The OCR accuracy is impressive (definitely 99%+ as claimed), table extraction works well, and batch processing saves tons of time. The handwriting recognition is surprisingly good. Would be nice to have more export format options, but for most use cases, this is perfect.',
    helpful: 34,
    notHelpful: 3,
    verified: true,
    timestamp: Date.now() - 5 * 24 * 60 * 60 * 1000
  }
]
